REHLIB := $(CURDIR)/librehlib.$(LIBRARY_SUFFIX)

SRC_SOURCES := _common.c refmem.c GBTError.c
SRC_SOURCES := $(SRC_SOURCES:%=$(CURDIR)/%)
SRC_OBJECTS := $(SRC_SOURCES:.c=.o)
SRC_DEPS := $(SRC_SOURCES:.c=.d)

REFMEM_SOURCES := refmem_test.c _common.c
REFMEM_SOURCES := $(REFMEM_SOURCES:%=$(CURDIR)/%)
REFMEM_OBJECTS := $(REFMEM_SOURCES:.c=.o)
REFMEM_DEPS := $(REFMEM_SOURCES:.c=.d)
REFMEM_LIB := $(CURDIR)/librefmem.$(LIBRARY_SUFFIX)

TESTS := $(TESTS) $(REFMEM_LIB)
